resources:
- server.yaml

generatorOptions:
  disableNameSuffixHash: true

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: edge-api
  newName: quay.io/project-flotta/flotta-edge-api
