log-level = "info"
cert-file = "/etc/pki/consumer/cert.pem"
key-file = "/etc/pki/consumer/key.pem"
ca-root = ["/etc/pki/consumer/ca.pem"]
path-prefix = "api/flotta-management/v1"
protocol = "http"
client-id = "$(cat /etc/machine-id)"
server = "project-flotta.io:$FLOTTA_PORT"
