---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: flotta-edge-api
  name: edge-api
  namespace: system
spec:
  host: REPLACE_HOST
  port:
    targetPort: yggds
  tls:
    termination: passthrough
  to:
    kind: Service
    name: flotta-operator-edge-api
    weight: 100
  wildcardPolicy: None
