## Append samples you want in your CSV to this file as resources ##
resources:
- management_v1alpha1_edgedevice.yaml
- management_v1alpha1_edgeworkload.yaml
- management_v1alpha1_edgedevicegroup.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
