apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: flotta

# Value of this field is prepended to the
# names of all resources, e.g. a deployment named
# "wordpress" becomes "alices-wordpress".
# Note that it should also match with the prefix (text before '-') of the namespace
# field above.
namePrefix: flotta-operator-
images:
- name: "gcr.io/kubebuilder/kube-rbac-proxy"
  newName: "registry.redhat.io/openshift4/ose-kube-rbac-proxy"
  newTag: "v4.9.0"
resources:
  - ../base
  - ../network
  - prometheus/prometheus_role.yaml
  - prometheus/prometheus_role_binding.yaml
  - prometheus/monitor.yaml

patchesJson6902:
  - target:
      group: route.openshift.io
      version: v1
      kind: Route
      name: controller-manager
    patch: |-
      - op: replace
        path: /spec/host
        value: project-flotta.io
