
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.4.1
  creationTimestamp: null
  name: edgeconfigs.management.project-flotta.io
spec:
  group: management.project-flotta.io
  names:
    kind: EdgeConfig
    listKind: EdgeConfigList
    plural: edgeconfigs
    singular: edgeconfig
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: EdgeConfig is the Schema for the edgeconfigs API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: EdgeConfigSpec defines the desired state of EdgeConfig
            properties:
              IgnitionConfig:
                description: IgnitionConfig is the config used by flotta config. By
                  default only user/systemd and a subset of filesystem are in place(directories,
                  links, files) The main reason to use in this way is because ignition
                  is only valid for startup, but some functions(described before)can
                  be used without issues
                format: byte
                type: string
              edgePlaybook:
                description: Definition of the custom playbook workload to execute
                properties:
                  playbooks:
                    description: The ansible's playbooks list. The first element is
                      the playbook with the highest priority.
                    items:
                      properties:
                        ansibleOptions:
                          description: the ansible's playbook options for the playbook
                          properties:
                            check:
                              description: don't make any changes; instead, try to
                                predict some of the changes that may occur
                              type: boolean
                          type: object
                        content:
                          description: Playbook content
                          format: byte
                          type: string
                        executionStrategy:
                          description: Execution strategy for the playbook
                          type: string
                        privilegeEscalationOptions:
                          description: the ansible's playbook privilege escalation
                            options for the playbook
                          properties:
                            become:
                              type: boolean
                            becomeMethod:
                              enum:
                              - sudo
                              - su
                              type: string
                            becomeUser:
                              type: string
                          type: object
                        requiredPrivilegeLevel:
                          description: The required privelege level necessary to execute
                            the playbook
                          properties:
                            capAdd:
                              description: See https://man7.org/linux/man-pages/man7/capabilities.7.html
                              items:
                                type: integer
                              type: array
                            capDrop:
                              items:
                                type: integer
                              type: array
                          type: object
                        timeoutSeconds:
                          description: The connection timeout on ansible-playbook
                          format: int64
                          type: integer
                      required:
                      - content
                      type: object
                    minItems: 1
                    type: array
                  user:
                    description: username who execute the playbook
                    type: string
                type: object
            type: object
          status:
            description: EdgeConfigStatus defines the observed state of EdgeConfig
            properties:
              edgePlaybookStatus:
                description: EdgePlaybookStatus defines the observed state of EdgePlaybook
                properties:
                  conditions:
                    items:
                      properties:
                        lastTransitionTime:
                          format: date-time
                          type: string
                        message:
                          type: string
                        reason:
                          type: string
                        status:
                          description: Indicates whether that condition is applicable,
                            with possible values "True", "False", or "Unknown" The
                            absence of a condition should be interpreted the same
                            as Unknown
                          type: string
                        type:
                          type: string
                      required:
                      - status
                      - type
                      type: object
                    type: array
                type: object
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
