
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.4.1
  creationTimestamp: null
  name: edgedevices.management.project-flotta.io
spec:
  group: management.project-flotta.io
  names:
    kind: EdgeDevice
    listKind: EdgeDeviceList
    plural: edgedevices
    singular: edgedevice
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: EdgeDevice is the Schema for the edgedevices API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: EdgeDeviceSpec defines the desired state of EdgeDevice
            properties:
              heartbeat:
                properties:
                  hardwareProfile:
                    description: hardware profile
                    properties:
                      include:
                        description: include
                        type: boolean
                      scope:
                        description: 'scope Enum: [full delta]'
                        type: string
                    type: object
                  periodSeconds:
                    description: period seconds
                    format: int64
                    type: integer
                type: object
              log_collection:
                additionalProperties:
                  properties:
                    buffer_size:
                      default: 12
                      format: int32
                      minimum: 1
                      type: integer
                    kind:
                      description: Kind is the type of log collection to be used
                      enum:
                      - syslog
                      type: string
                    syslog_config:
                      description: SyslogConfig is the pointer to the configMap to
                        be used to load the config
                      properties:
                        name:
                          type: string
                      required:
                      - name
                      type: object
                  type: object
                type: object
              metrics:
                properties:
                  retention:
                    properties:
                      maxHours:
                        description: MaxHours specifies how long should persisted
                          metrics be stored on the device disk
                        format: int32
                        minimum: 0
                        type: integer
                      maxMiB:
                        description: MaxMiB specifies how much disk space should be
                          used for storing persisted metrics on the device
                        format: int32
                        minimum: 0
                        type: integer
                    type: object
                  system:
                    properties:
                      allowList:
                        description: AllowList defines name of a ConfigMap containing
                          list of system metrics that should be scraped
                        properties:
                          name:
                            type: string
                        required:
                        - name
                        type: object
                      disabled:
                        description: Disabled when set to true instructs the device
                          to turn off system metrics collection
                        type: boolean
                      interval:
                        default: 60
                        description: Interval(in seconds) to scrape system metrics.
                        format: int32
                        minimum: 0
                        type: integer
                    type: object
                type: object
              osInformation:
                description: OsInformation carries information about commit ID of
                  the OS Image deployed to the device
                properties:
                  automaticallyUpgrade:
                    description: Automatically upgrade the OS image
                    type: boolean
                  commitID:
                    description: CommitID carries information about commit of the
                      OS Image
                    type: string
                  hostedObjectsURL:
                    description: HostedObjectsURL carries the URL of the hosted commits
                      web server
                    type: string
                type: object
              requestTime:
                description: RequestTime is the time of device registration request
                format: date-time
                type: string
              storage:
                properties:
                  s3:
                    properties:
                      configMapName:
                        description: configMap name
                        type: string
                      createOBC:
                        description: createOBC. if the configuration above is empty
                          and this bool is true then create OBC
                        type: boolean
                      secretName:
                        description: secret name
                        type: string
                    type: object
                type: object
            type: object
          status:
            description: EdgeDeviceStatus defines the observed state of EdgeDevice
            properties:
              dataObc:
                type: string
              deployments:
                items:
                  properties:
                    lastDataUpload:
                      format: date-time
                      type: string
                    lastTransitionTime:
                      format: date-time
                      type: string
                    name:
                      type: string
                    phase:
                      type: string
                  required:
                  - name
                  type: object
                type: array
              hardware:
                properties:
                  boot:
                    description: boot
                    properties:
                      currentBootMode:
                        description: current boot mode
                        type: string
                      pxeInterface:
                        description: pxe interface
                        type: string
                    type: object
                  cpu:
                    description: cpu
                    properties:
                      architecture:
                        description: architecture
                        type: string
                      count:
                        description: count
                        format: int64
                        type: integer
                      flags:
                        description: flags
                        items:
                          type: string
                        type: array
                      frequency:
                        description: frequency
                        type: string
                      modelName:
                        description: model name
                        type: string
                    required:
                    - flags
                    type: object
                  disks:
                    description: disks
                    items:
                      properties:
                        bootable:
                          description: bootable
                          type: boolean
                        byId:
                          description: by-id is the World Wide Number of the device
                            which guaranteed to be unique for every storage device
                          type: string
                        byPath:
                          description: by-path is the shortest physical path to the
                            device
                          type: string
                        driveType:
                          description: drive type
                          type: string
                        hctl:
                          description: hctl
                          type: string
                        id:
                          description: Determine the disk's unique identifier which
                            is the by-id field if it exists and fallback to the by-path
                            field otherwise
                          type: string
                        ioPerf:
                          description: io perf
                          properties:
                            syncDuration:
                              description: 99th percentile of fsync duration in milliseconds
                              format: int64
                              type: integer
                          type: object
                        isInstallationMedia:
                          description: Whether the disk appears to be an installation
                            media or not
                          type: boolean
                        model:
                          description: model
                          type: string
                        name:
                          description: name
                          type: string
                        path:
                          description: path
                          type: string
                        serial:
                          description: serial
                          type: string
                        sizeBytes:
                          description: size bytes
                          format: int64
                          type: integer
                        smart:
                          description: smart
                          type: string
                        vendor:
                          description: vendor
                          type: string
                        wwn:
                          description: wwn
                          type: string
                      type: object
                    type: array
                  gpus:
                    description: gpus
                    items:
                      properties:
                        address:
                          description: Device address (for example "0000:00:02.0")
                          type: string
                        deviceId:
                          description: ID of the device (for example "3ea0")
                          type: string
                        name:
                          description: Product name of the device (for example "UHD
                            Graphics 620 (Whiskey Lake)")
                          type: string
                        vendor:
                          description: The name of the device vendor (for example
                            "Intel Corporation")
                          type: string
                        vendorId:
                          description: ID of the vendor (for example "8086")
                          type: string
                      type: object
                    type: array
                  hostname:
                    description: hostname
                    type: string
                  interfaces:
                    description: interfaces
                    items:
                      properties:
                        biosdevname:
                          description: biosdevname
                          type: string
                        clientId:
                          description: client id
                          type: string
                        flags:
                          description: flags
                          items:
                            type: string
                          type: array
                        hasCarrier:
                          description: has carrier
                          type: boolean
                        ipv4Addresses:
                          description: ipv4 addresses
                          items:
                            type: string
                          type: array
                        ipv6Addresses:
                          description: ipv6 addresses
                          items:
                            type: string
                          type: array
                        macAddress:
                          description: mac address
                          type: string
                        mtu:
                          description: mtu
                          format: int64
                          type: integer
                        name:
                          description: name
                          type: string
                        product:
                          description: product
                          type: string
                        speedMbps:
                          description: speed mbps
                          format: int64
                          type: integer
                        vendor:
                          description: vendor
                          type: string
                      required:
                      - flags
                      type: object
                    type: array
                  memory:
                    description: memory
                    properties:
                      physicalBytes:
                        description: physical bytes
                        format: int64
                        type: integer
                      usableBytes:
                        description: usable bytes
                        format: int64
                        type: integer
                    type: object
                  systemVendor:
                    description: system vendor
                    properties:
                      manufacturer:
                        description: manufacturer
                        type: string
                      productName:
                        description: product name
                        type: string
                      serialNumber:
                        description: serial number
                        type: string
                      virtual:
                        description: Whether the machine appears to be a virtual machine
                          or not
                        type: boolean
                    type: object
                required:
                - disks
                - gpus
                - interfaces
                type: object
              lastSeenTime:
                format: date-time
                type: string
              lastSyncedResourceVersion:
                type: string
              phase:
                type: string
              upgradeInformation:
                properties:
                  currentCommitID:
                    description: Current commit
                    type: string
                  lastUpgradeStatus:
                    description: last upgrade status
                    type: string
                  lastUpgradeTime:
                    description: last upgrade time
                    type: string
                required:
                - currentCommitID
                type: object
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
